---
- name: add docker-ce repo
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: install containerd
  dnf:
    name: 'https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm'
    state: present

- name: install docker-ce
  dnf:
    name: docker-ce
    state: latest

- name: start and enable docker-ce
  service:
    name: docker
    state: started
    enabled: true

- name: add k8s repo
  copy:
    src: "{{ role_path }}/files/k8s.repo"
    dest: /etc/yum.repos.d/k8s.repo
    mode: 0700
