---
- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: disable selinux
  selinux:
    state: disabled

- name: disable swap (cli)
  shell: |
      swapoff -a

- name: disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
