---
- name: activate br_netfilter
  shell: |
    modprobe br_netfilter

- name: brige config
  copy:
    src: "{{ role_path }}/files/k8s.conf"
    dest: /etc/sysctl.d/k8s.conf
    mode: 0700

- name: activate iptables bridge traffic
  shell: |
    sysctl --system


- name: disable swap
  shell: |
    swapoff -a

- name: disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: disable selinux
  selinux:
    policy: targeted
    state: disabled

- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false
